<?php

namespace App\Models;

use App\Models\Admin\Post;
use App\Models\Image as Img;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Image extends Model
{
    use HasFactory;
    protected $fillable = [
        'url',
        'post_id',
        'user_id'
    ];

    public function delete()
    {
        $old = $this->url;
        if ($old) {
            Storage::disk('public')->delete('u_images/' . $old);
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function author(){

        return User::find($this->user_id);

    }

    public function post(){

        return Post::find($this->post_id);

    }
}
